# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TLS
                                 A QGIS plugin
 This plugin offers multiple tiff loading and styling
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-11-14
        copyright            : (C) 2023 by Riccardo Klinger
        email                : riccardo.klinger@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Riccardo Klinger'
__date__ = '2023-11-14'
__copyright__ = '(C) 2023 by Riccardo Klinger'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TLS class from file TLS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .tls import TLSPlugin
    return TLSPlugin()
